### ISSUE TITLE
Project needs a catchy name / acronym

### ISSUE THREAD

**Issue by runspired** [runspired/warp-drive#1]
A few suggestions so far.
- Ember Known Good "EKG"
- Ember Drive "ED"
- Grouse "G"
- Ember Core Data "ECD"
- Latency Slow Down "LSD"

**Comment by twokul** [comment]
Ember Drive might be confusing (Ember Data is also ED). I like Ember Core Data.

**Comment by arjunkathuria** [comment]
is `Ember-Warp`, already a thing ?

**Comment by runspired** [comment]
ooooh, I do love StarTrek

**Comment by landongn** [comment]
Ember Database Modeler (EDM!) 💃

**Comment by runspired** [comment]
Published as `warp-drive v0.0.0-beta.1` 💃

There's still a ways to go before that beta is anything more than a glorious speed demo.

@landongn I did like EDM :D
